version: '3.7'

x-build: &build
  build:
    context: .
    cache_from:
      - moloney_collection
      - quay.io/nyulibraries/moloney_collection
      - quay.io/nyulibraries/moloney_collection:$BRANCH_NO_SLASH
  image: moloney_collection
x-dev-env: &dev-env
  <<: *build
  environment:
    BRANCH_NO_SLASH:
    CI:
    TERM: xterm
    PAGER: more
    MOLONEY_DB_HOST: db
    MOLONEY_DB_DATABASE: moloney
    MOLONEY_DB_USER: root
    MOLONEY_DB_PASSWORD:
    GIT_COMMIT:
    DEPLOY_ENV:

services:
  dev:
    <<: *dev-env
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - setup_dev
    volumes: 
      - .:/app

  setup_dev:
    <<: *dev-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
    - ./moloney_dev.sql:/app/moloney_dev.sql

    # WORKING WITH SQL DATA DUMPS LOCALLY:
    # docker run -it library/mysql:5.6.22 bash
    # mysqldump --user={username} -p --host={web.hostdomain.com} moloney > moloney_dev.sql
    # docker cp {CONTAINER_ID}:/app/moloney_dev.sql moloney_dev.sql
    # docker-compose up dev
    # docker-compose exec db  bash -c 'mysql -uroot --host=db moloney < /app/moloney_dev.sql'

  deploy:
    <<: *dev-env
    tty: true
    stdin_open: true
    command: "mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts && \
              bundle exec cap $DEPLOY_ENV deploy:setup && bundle exec cap $DEPLOY_ENV deploy"
    user: root
    environment:
      SSH_AUTH_SOCK: '/ssh-agent'
      GIT_COMMIT: "$GIT_COMMIT"
    volumes:
      - "${HOST_SSH_AUTH_SOCK}:/ssh-agent"